name: CI

on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

jobs:
 test:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3

     - name: Set up Go
       uses: actions/setup-go@v4
       with:
         go-version: '1.21'

     - name: Check format
       run: |
         if [ -n "$(gofmt -l .)" ]; then
           echo "Files not properly formatted:"
           gofmt -l .
           exit 1
         fi

     - name: Test
       run: |
         go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

     - name: Upload coverage
       uses: codecov/codecov-action@v3
       with:
         file: ./coverage.txt